//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package xps.impl.document.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_Story complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_Story">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}StoryFragmentReference" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}AG_Story"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_Story", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", propOrder = {
    "storyFragmentReference"
})
public class CTStory {

    @XmlElement(name = "StoryFragmentReference", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", required = true)
    protected List<CTStoryFragmentReference> storyFragmentReference;
    @XmlAttribute(name = "StoryName", required = true)
    protected String storyName;

    /**
     * Gets the value of the storyFragmentReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storyFragmentReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStoryFragmentReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTStoryFragmentReference }
     * 
     * 
     */
    public List<CTStoryFragmentReference> getStoryFragmentReference() {
        if (storyFragmentReference == null) {
            storyFragmentReference = new ArrayList<CTStoryFragmentReference>();
        }
        return this.storyFragmentReference;
    }

    /**
     * Gets the value of the storyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoryName() {
        return storyName;
    }

    /**
     * Sets the value of the storyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoryName(String value) {
        this.storyName = value;
    }

}
